env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
setting:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
rules:
  {
    'react/jsx-filename-extension': [1, { 'extensions': ['.tsx', '.jsx'] }],
    'comma-dangle': 0,
  }
